[package]
name = "wgpu_bug"
version = "0.1.0"
authors = ["tasgon <tasgon_@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.7"
pollster = "0.2"